Adds delete node code snippets to the cheatsheet.md
kanopi/cypress_starter pull request #16
Opened 2023-12-01 18:57 UTC by Stockfoot

## Description
Related Drupal Issue(s): [Add to Cheatsheet: User/User Role can delete a piece of content](https://www.drupal.org/project/shrubs/issues/3402918)

**This PR adds 2 items to the cheatsheet**
- Delete content from node page
- Delete content from node edit page

2023-12-03 13:15 UTC, thejimbirch requested changes

2023-12-03 13:15 UTC, thejimbirch commented on CHEATSHEET.md
> +cy.get('.button--danger').click();
Can we change this to `.contains('Delete')` also?  `.button--danger` may not be on all admin themes.

2023-12-03 13:15 UTC, thejimbirch commented on CHEATSHEET.md
> +```markdown
We need a visit command here first.

// Visit a node
cy.visit('node/[nodeID]')

2023-12-03 13:15 UTC, thejimbirch commented on CHEATSHEET.md
> +cy.get('h1').should('contain', 'Hamilton Educational Website');
This is too specific.  Is there another way we can validate the deletion?  If not, please update this to say something like `Your Page Title`.

2023-12-03 13:15 UTC, thejimbirch commented on CHEATSHEET.md
> +```
Awesome!

2023-12-08 19:05 UTC, paulsheldrake commented
There may be a new support function here...  something like

```
deleteNode($title) {
visit(/admin/content)
search filter for title
click delete in the options
check yes
}
```

it would require that user have permissions to the content overview page

2023-12-21 16:59 UTC, thejimbirch approved these changes

2023-12-21 16:59 UTC, merged