Initial cypress examples for cheatsheet
kanopi/cypress_starter pull request #8
Opened 2023-09-29 19:50 UTC by Devonjedi

## Description
> As a developer, I need to start with a story.

_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR? **Include your acceptance critiera!** If your tasks were well-written, you can probably copy/paste some of this._

## Affected URL
[link_to_relevant_multidev_or_test_site](insert_link_here)

## Related Tickets

* [insert_ticket_name_here](insert_link_here)

## Steps to Validate
1. A list of steps to validate
1. Include direct links to test sites -- specific nodes, admin screens, etc
1. Be explicit

## Deploy Notes

_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._

2023-09-29 22:46 UTC, paulsheldrake commented on CHEATSHEET.md
> +Cypress.Commands.add("ckeditorType", (selector, content) => {
Link to the support command src code instead of copying it

2023-10-12 17:06 UTC, thejimbirch requested changes

2023-10-12 17:06 UTC, thejimbirch commented on CHEATSHEET.md
>  * Log into Drupal
Can you change all these bullets to H3s?

### Log into Drupal

2023-10-12 17:06 UTC, thejimbirch commented on CHEATSHEET.md
> +cy.login('User', 'pass')
For single line code, wrap them in single `

`cy.login('User', 'pass')`

2023-10-12 17:06 UTC, thejimbirch commented on CHEATSHEET.md
>  * Create a Paragraph
For multiple line code blocks, ass ```

```
cy.visit('/node/123/edit');

cy.get('.add-paragraph-button').click();

cy.get('#edit-paragraph-field-name').type('My Paragraph Name');
// Fill in other paragraph fields here
cy.get('#edit-submit').click();
```

2023-10-13 11:39 UTC, thejimbirch approved these changes
Great job, thanks!

2023-10-13 11:39 UTC, merged